# Additions

## Executive summary

An addition occurs whan a non-originally placed item is added to an order. However, this product should not be the replacement of another. A common example of additions are plastic bags that need to be added to an order. In data terms, additions create 2 registres in bought products. A first register with the product with quantity zero, which is replaced by a product with the same external id and quantity greater than zero.

During the last 30 days, in Groceries partners, around 20% of orders contain additions.


**Business questions answered:**

- **How do additions differentiate to price mismatch?** --> Additions create 2 registers in bought products table. The first one with quantity 0. The second one with quantity >0. However, the price mismatch also has to registers in bought products table. The first one with quantity>0, and the second register with quantity <> quantity of the first register

- **How do additions differentiate to replacements?** --> Additions create 2 registers with the same external id. Replcaments have 2 registers with different external id^

- **How do price mismatch and partial removal differentiate?** --> There is no way to distinguish. Both create 2 registers, and change the quantity of the products. Obviously, in both scenarios the final price of the product will have change. Thus, we cannot actively differentiate between price mismatch and partial removal

## Plan

Business question to answer
- [X] What is the % of orders with additions
- [X] How do additions differentiate to price mismatch
- [X] How do additions differentiate to replacements

Tasks
- [X] Develop a query to identify additions
- [X] Idenfity example of additions, price mismatch, replacements, removals... 
- [X] Compute % of orders with additions
- [ ] Adapt Muhammad query to extract desired values

Conclusions
- [X] Complete executive summary
- [X] Anything to add to template
- [X] Any query to add to repo

## Config

In [1]:
import sys
import pandas

sys.path.append('c:\\Users\\Jordi Cremades\\Documents\\Repository')

from utils import query_engines

## Task 1: Develop a query to identify additions

In [29]:
#query object
q = query_engines.QueryEngines(
    query='bought_product_is_addition.sql', 
    params=None,
    load_from_output_file=None, #with no .csv
    output_file=None, #with no .csv
    printq=None
)

df = q.query_run_starbust()

c:\Users\Jordi Cremades\Documents\Repository\utils\query_engines.py:145: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(self.tp__read_query, conn)

Open the following URL in browser for the external authentication:
https://starburst.g8s-data-platform-prod.glovoint.com/oauth2/token/initiate/a5c9cd541d424ab0eb5e40098718d3682e212b84f763a28b0e79d9ec42456768

Replacement

In [30]:
#replacement
tmp = df.copy()

cond = tmp['order_id'] == 100308613825
cols = ['order_id'
        ,'product_name'
        ,'product_id'
        ,'bought_product_id'
        ,'product_external_id'
        ,'bought_product_quantity'
        ,'replaced_by_bought_product_id'
        ,'replaced_bought_product_id'
        ,'has_an_addition'
        ,'added_quantity'
        ]


tmp = tmp[cond].loc[:, cols]

#transform a float column to an integers
tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].fillna('').astype(str)
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].fillna('').astype(str)

tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].apply(lambda x: int(float(x)) if x else '')
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].apply(lambda x: int(float(x)) if x else '')

tmp

,order_id,product_name,product_id,bought_product_id,product_external_id,bought_product_quantity,replaced_by_bought_product_id,replaced_bought_product_id,has_an_addition,added_quantity
13,100308613825,Hogaza Maíz Y Espelta 900 Gr.,23165893587,104815419975,146,1,104815492649,,False,NaN
41,100308613825,Barra De Pan Rústica 300 Gr.,23165893848,104815419974,851,2,,,False,NaN
42,100308613825,Hogaza Espelta Blanca (Aprox. 800 Gr.),23165893572,104815492649,128,1,,104815419975,False,NaN

Addition

In [32]:
#addition
tmp = df.copy()

cond = tmp['order_id'] == 628322096
cols = ['order_id'
        ,'product_name'
        ,'product_id'
        ,'bought_product_id'
        ,'product_external_id'
        ,'bought_product_quantity'
        ,'replaced_by_bought_product_id'
        ,'replaced_bought_product_id'
        ,'has_an_addition'
        ,'added_quantity'
        ]


tmp = tmp[cond].loc[:, cols]

#transform a float column to an integers
tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].fillna('').astype(str)
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].fillna('').astype(str)

tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].apply(lambda x: int(float(x)) if x else '')
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].apply(lambda x: int(float(x)) if x else '')

tmp

,order_id,product_name,product_id,bought_product_id,product_external_id,bought_product_quantity,replaced_by_bought_product_id,replaced_bought_product_id,has_an_addition,added_quantity
0,628322096,Bolsa De Caja Reciclable +55,14850415464,100097782274,181ae699-28b3-4949-bb88-c35cbf8f0ed1,0,100097782275,,True,5.0
1,628322096,Café Qualita Oro Lavazza Caja 250 G,15527735414,100097688277,18680975,3,,,False,NaN
25,628322096,"Copos De Avena Integrales Eroski Bio, Paquete ...",15527721158,100097688284,23848567,1,,,False,NaN
26,628322096,"Papel Higiénico Scottex Megarollo, Paquete 9 R...",15527802931,100097688283,17028994,1,,,False,NaN
27,628322096,Tortitas 8U Zanuy Flour 315G,15527668586,100097688281,10955896,1,,,False,NaN
28,628322096,Queso President Brie Puntas 200 Gr.,15527578719,100097688279,219238,1,,,False,NaN
29,628322096,Mantequilla Con Sal Eroski Patilla 250 Gr.,15527571036,100097688278,15636483,1,,,False,NaN
30,628322096,"Tomate Cherry, Bandeja 500 G",15527859256,100097688292,24940132,1,,,False,NaN
31,628322096,Arroz Sabroz Brillante 1Kg,15527632124,100097688287,14863369,2,,,False,NaN
32,628322096,Bombón Double De Caramelo Magnum 3 Uds. 219 Gr.,15527742845,100097688290,18580076,1,,,False,NaN
33,628322096,Bolsa De Caja Reciclable +55,14850415464,100097782275,181ae699-28b3-4949-bb88-c35cbf8f0ed1,5,,100097782274,False,NaN
34,628322096,Cebolla Blanca Tubo 1Kg.,15527556469,100097688280,1934785,1,,,False,NaN
35,628322096,"Abrillantador Eco 0% Finish, Botella 400 Dosis",15527808349,100097688291,23335755,1,,,False,NaN
36,628322096,Leche Asturiana Combi Entera 1 L.,15527556550,100097688285,735423,7,,,False,NaN
37,628322096,Uva Blanca Sin Semilla Cubeta 500 G,15527549292,100097688289,17778762,1,,,False,NaN
38,628322096,Leche Desnatada 0% Sin Lactosa M. G. Asturiana...,15527556412,100097688286,16560666,3,,,False,NaN
39,628322096,Zanahorias Bolsa 500G,15527549390,100097688282,4501375,1,,,False,NaN
40,628322096,Pera Conferencia De Cataluña Barqueta 1 Kg,15527549358,100097688288,23833817,1,,,False,NaN

Price mismatch

In [33]:
#price mismatch
tmp = df.copy()

cond = tmp['order_id'] == 100382450564
cols = ['order_id'
        ,'product_name'
        ,'product_id'
        ,'bought_product_id'
        ,'product_external_id'
        ,'bought_product_quantity'
        ,'replaced_by_bought_product_id'
        ,'replaced_bought_product_id'
        ,'has_an_addition'
        ,'added_quantity'
        ]


tmp = tmp[cond].loc[:, cols]

#transform a float column to an integers
tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].fillna('').astype(str)
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].fillna('').astype(str)

tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].apply(lambda x: int(float(x)) if x else '')
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].apply(lambda x: int(float(x)) if x else '')

tmp

,order_id,product_name,product_id,bought_product_id,product_external_id,bought_product_quantity,replaced_by_bought_product_id,replaced_bought_product_id,has_an_addition,added_quantity
14,100382450564,"Mleczna Dolina Masło Ekstra bez laktozy 82%, 2...",24083945264,105352420838,287045,1,,,False,NaN
15,100382450564,"Cukier biały, 1 kg",23833875690,105352420858,291534,1,,,False,NaN
16,100382450564,"Bonitki Sezamki Classic, 3x27 g",21328063111,105352420841,286678,1,,,False,NaN
17,100382450564,"Mleczna Dolina Mleko UHT bezlaktozy 3,2%, 1 L",24888235704,105352420845,283084,2,,,False,NaN
18,100382450564,"Nestlé Cheerios Płatki śniadaniowe, 275 g",23794199926,105352420846,1082,1,,,False,NaN
19,100382450564,"Delicje Szampańskie pomarańczowe, 147 g",19636840435,105352420822,307686,1,,,False,NaN
20,100382450564,"Cukiernia Róża Rurki waflowe Waniliowe, 280 g",24502714041,105352420842,2042631,2,,,False,NaN
21,100382450564,"Kamis Przyprawa do mięsa mielonego, 20 g",17434756134,105352420827,358746,1,,,False,NaN
22,100382450564,Torba T-shirt BIEK 1 szt,24279534084,105352522441,409893,0,105352522442,,True,4.0
23,100382450564,"Nasze Smaki Pierogi z mięsem i cebulką bowl, 3...",24888227069,105352420824,384891,1,,,False,NaN
43,100382450564,"Tchibo Family Kawa mielona, 500 g",13068511144,105352420852,201996,1,,,False,NaN
44,100382450564,GustoBello Pomidory krojone z cebulą i czosnki...,24888227068,105352420825,3790292,1,,,False,NaN
45,100382450564,"TOP Tortilla Chipsy serowe, 150 g",24923174381,105352420854,2076032,1,,,False,NaN
46,100382450564,Aril Świeca zapachowa w szkle frezja i gruszka...,24011061932,105352420821,3773732,1,,,False,NaN
47,100382450564,"Fruvita Jogurt z granolą i truskawkami, 230 g",23975114144,105352420833,3609811,1,,,False,NaN
48,100382450564,"Drobimex Pierś pieczona, 100 g",24402333549,105352420828,2830101,1,,,False,NaN
49,100382450564,"Pastani Makaron durum Penne, 500 g",24573432699,105352420848,195157,1,,,False,NaN
50,100382450564,"Mlekovita Mleko czekoladowe, 200 ml",24702088018,105352420823,302440,1,,,False,NaN
51,100382450564,"Nasze Smaki Pierogi z serem, 400 g",24193843155,105352420843,265027,2,,,False,NaN
52,100382450564,Zosia Samosia Woreczki śniadaniowe zawiązywane...,16212495423,105352420856,298597,1,,,False,NaN
53,100382450564,"Żywiec Zdrój Woda źródlana mocno gazowana, 1,75 L",24279536124,105352420850,208155,1,,,False,NaN
54,100382450564,Blend-a-med Pasta do zębów 3D White Extreme Mi...,24888235727,105352420839,4139052,1,,,False,NaN
55,100382450564,"Milka Pieguski Ciastka z czekoladą, 300 g",24888226745,105352420844,275701,1,,,False,NaN
56,100382450564,"Dare Wafel w ciemnej czekoladzie, 50 g",17907358205,105352420835,382057,2,,,False,NaN
57,100382450564,"Queen Papier Toaletowy Premium Super Soft, 10 ...",24279536944,105352420829,358909,1,,,False,NaN
58,100382450564,"Vital Fresh Smoothie imbir jabłko banan kokos,...",24888235745,105352420826,477627,1,,,False,NaN
59,100382450564,"Mr Potato Ziemniaczki, 750 g",24193843392,105352420851,206432,1,,,False,NaN
60,100382450564,"Drobimex Szynka delikatesowa z kurcząt, 100 g",24534005537,105352420857,2830102,2,,,False,NaN
61,100382450564,"Culineo Sól warzona jodowana, 1 kg",24502714625,105352420860,198521,1,,,False,NaN
62,100382450564,"Fairy Sensitive Płyn do mycia naczyń, drzewo h...",24702087736,105352420855,4284804,1,,,False,NaN
63,100382450564,"Milka Czekolada Toffee Wholenut, 300 g",24573431189,105352420832,2594092,1,,,False,NaN
64,100382450564,"Bataty Słodkie ziemniaki, 1 szt. ok. 350 g, 9,...",24888235886,105352420831,266649,1,,,False,NaN
65,100382450564,"TOP Chrupki z soczewicy paprykowe, 70 g",22687889597,105352420859,4097891,1,,,False,NaN
66,100382450564,"Delikate Serek wiejski klasyczny, bez laktozy,...",24193843272,105352420853,279090,1,,,False,NaN
67,100382450564,"Pastani Makaron durum Fusilli, 500 g",24402337508,105352420830,195158,1,,,False,NaN
68,100382450564,"Sierpc Ser żółty Królewski Light w plastrach, ...",24888226751,105352420847,3023331,1,,,False,NaN
69,100382450564,Torba T-shirt BIEK 1 szt,24279534084,105352522442,409893,4,,105352522441,False,NaN
70,100382450564,"Torebka na wino, 1 szt.",22730006781,105352420836,25218117,1,,,False,NaN
71,100382450564,"Wedel Wafelek WW w mlecznej czekoladzie, 47 g",24502715069,105352420840,278495,1,,,False,NaN
72,100382450564,"Herbapol Mięta, 20 torebek",18848941869,105352420849,421252,1,,,False,NaN
73,100382450564,"Cebula Szalotka, 1 szt. ok. 50 g, 9,90/kg",24356175124,105352522429,370188,3,,105352420837,False,NaN
74,100382450564,"Hellena Oranżada czerwona, 1,25 L",23299653858,105352420834,463780,1,,,False,NaN
75,100382450564,"Cebula Szalotka, 1 szt. ok. 50 g, 9,90/kg",24356175124,105352420837,370188,2,105352522429,,True,1.0

Query to identify products with additions

In [35]:
#query object
q = query_engines.QueryEngines(
    query='bought_product_has_addition.sql', 
    params=None,
    load_from_output_file=None, #with no .csv
    output_file=None, #with no .csv
    printq=None
)

df = q.query_run_starbust()

c:\Users\Jordi Cremades\Documents\Repository\utils\query_engines.py:145: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(self.tp__read_query, conn)

Open the following URL in browser for the external authentication:
https://starburst.g8s-data-platform-prod.glovoint.com/oauth2/token/initiate/f768f70068ea8b309f3d070195174fe1d4c7914bfe5d583a92c910d59a60c75f

In [36]:
df

,bought_product_id,product_id,order_id,store_address_id,product_external_id,product_name,product_weight_in_kg,product_unit_price,bought_product_quantity,product_category,...,product_is_alcoholic,product_is_tobacco,collection_section_name,collection_name,collection_group_name,bought_product_created_at,bought_product_updated_at,p_creation_date,has_an_addition,added_quantity
0,1725294747,14850440271,596405134,498575,181ae699-28b3-4949-bb88-c35cbf8f0ed1,Bolsa De Caja Reciclable +55,0.0,0.15,1,None,...,False,False,,,,2023-04-06 11:51:25+00:00,2023-04-06 11:51:25+00:00,2023-04-06,True,1
1,100097782274,14850415464,628322096,484173,181ae699-28b3-4949-bb88-c35cbf8f0ed1,Bolsa De Caja Reciclable +55,0.0,0.15,0,None,...,None,None,,,,2023-05-28 14:43:15+00:00,2023-05-28 14:43:15+00:00,2023-05-28,True,5
2,105352522441,24279534084,100382450564,336875,409893,Torba T-shirt BIEK 1 szt,NaN,0.59,0,None,...,False,False,Torby i reklamówki,Inne,Dla domu i zwierząt,2024-01-28 21:54:50+00:00,2024-01-28 21:54:50+00:00,2024-01-28,True,4
3,105352420837,24356175124,100382450564,336875,370188,"Cebula Szalotka, 1 szt. ok. 50 g, 9,90/kg",NaN,0.50,2,None,...,False,False,"Warzywa,Kuchnia francuska","Kuchnie świata,Warzywa i zioła","Mam ochotę na...,Owoce i warzywa",2024-01-28 21:42:19+00:00,2024-01-28 21:42:19+00:00,2024-01-28,True,1

## Task 2: Identify examples of all scenarios

In [22]:
# The following order_ids are examples of:

# Replacement: A new product is added to substitute an existing one
# order_id: 100308613825

# Replacement of an addition: A new product is added and then it is replaced
# order_id: 596405134

# Addition: A new product is added
# order_id: 628322096

# Price mismatch: An existing product is replaced for another one with a slight price modification. Common in weighted items
# order_id: 100382450564

In [83]:
#query object
q = query_engines.QueryEngines(
    query='bought_products_info.sql', 
    params=None,
    load_from_output_file='bp_info', #with no .csv
    output_file='bp_info', #with no .csv
    printq=None
)

df = q.query_run_starbust()

c:\Users\Jordi Cremades\Documents\Repository\utils\query_engines.py:145: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(self.tp__read_query, conn)

Open the following URL in browser for the external authentication:
https://starburst.g8s-data-platform-prod.glovoint.com/oauth2/token/initiate/f8fcd00bead5e4fd28b237a2c06d3588b08ab7f41eb87077bf98d38815080b1c

Replacement

In [92]:
#replacement
tmp = df.copy()

cond = tmp['order_id'] == 100308613825
cols = ['order_id'
        ,'product_name'
        ,'product_id'
        ,'bought_product_id'
        ,'product_external_id'
        ,'bought_product_quantity'
        ,'replaced_by_bought_product_id'
        ,'replaced_bought_product_id'
        ]


tmp = tmp[cond].loc[:, cols]

#transform a float column to an integers
tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].fillna('').astype(str)
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].fillna('').astype(str)

tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].apply(lambda x: int(float(x)) if x else '')
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].apply(lambda x: int(float(x)) if x else '')

tmp

,order_id,product_name,product_id,bought_product_id,product_external_id,bought_product_quantity,replaced_by_bought_product_id,replaced_bought_product_id
73,100308613825,Barra De Pan Rústica 300 Gr.,23165893848,104815419974,851,2,,
74,100308613825,Hogaza Espelta Blanca (Aprox. 800 Gr.),23165893572,104815492649,128,1,,104815419975
75,100308613825,Hogaza Maíz Y Espelta 900 Gr.,23165893587,104815419975,146,1,104815492649,

Addition

In [96]:
#addition
tmp = df.copy()

cond = tmp['order_id'] == 628322096
cols = ['order_id'
        ,'product_name'
        ,'product_id'
        ,'bought_product_id'
        ,'product_external_id'
        ,'bought_product_quantity'
        ,'replaced_by_bought_product_id'
        ,'replaced_bought_product_id'
        ]


tmp = tmp[cond].loc[:, cols]

#transform a float column to an integers
tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].fillna('').astype(str)
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].fillna('').astype(str)

tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].apply(lambda x: int(float(x)) if x else '')
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].apply(lambda x: int(float(x)) if x else '')

tmp

,order_id,product_name,product_id,bought_product_id,product_external_id,bought_product_quantity,replaced_by_bought_product_id,replaced_bought_product_id
0,628322096,Café Qualita Oro Lavazza Caja 250 G,15527735414,100097688277,18680975,3,,
23,628322096,"Copos De Avena Integrales Eroski Bio, Paquete ...",15527721158,100097688284,23848567,1,,
24,628322096,"Papel Higiénico Scottex Megarollo, Paquete 9 R...",15527802931,100097688283,17028994,1,,
25,628322096,Tortitas 8U Zanuy Flour 315G,15527668586,100097688281,10955896,1,,
26,628322096,Queso President Brie Puntas 200 Gr.,15527578719,100097688279,219238,1,,
27,628322096,Mantequilla Con Sal Eroski Patilla 250 Gr.,15527571036,100097688278,15636483,1,,
28,628322096,"Tomate Cherry, Bandeja 500 G",15527859256,100097688292,24940132,1,,
29,628322096,Arroz Sabroz Brillante 1Kg,15527632124,100097688287,14863369,2,,
30,628322096,Bombón Double De Caramelo Magnum 3 Uds. 219 Gr.,15527742845,100097688290,18580076,1,,
31,628322096,Bolsa De Caja Reciclable +55,14850415464,100097782274,181ae699-28b3-4949-bb88-c35cbf8f0ed1,0,100097782275,
32,628322096,Bolsa De Caja Reciclable +55,14850415464,100097782275,181ae699-28b3-4949-bb88-c35cbf8f0ed1,5,,100097782274
33,628322096,Cebolla Blanca Tubo 1Kg.,15527556469,100097688280,1934785,1,,
34,628322096,"Abrillantador Eco 0% Finish, Botella 400 Dosis",15527808349,100097688291,23335755,1,,
35,628322096,Leche Asturiana Combi Entera 1 L.,15527556550,100097688285,735423,7,,
36,628322096,Uva Blanca Sin Semilla Cubeta 500 G,15527549292,100097688289,17778762,1,,
37,628322096,Leche Desnatada 0% Sin Lactosa M. G. Asturiana...,15527556412,100097688286,16560666,3,,
38,628322096,Zanahorias Bolsa 500G,15527549390,100097688282,4501375,1,,
39,628322096,Pera Conferencia De Cataluña Barqueta 1 Kg,15527549358,100097688288,23833817,1,,

Price mismatch

In [97]:
#price mismatch
tmp = df.copy()

cond = tmp['order_id'] == 100382450564
cols = ['order_id'
        ,'product_name'
        ,'product_id'
        ,'bought_product_id'
        ,'product_external_id'
        ,'bought_product_quantity'
        ,'replaced_by_bought_product_id'
        ,'replaced_bought_product_id'
        ]


tmp = tmp[cond].loc[:, cols]

#transform a float column to an integers
tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].fillna('').astype(str)
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].fillna('').astype(str)

tmp['replaced_by_bought_product_id'] = tmp['replaced_by_bought_product_id'].apply(lambda x: int(float(x)) if x else '')
tmp['replaced_bought_product_id'] = tmp['replaced_bought_product_id'].apply(lambda x: int(float(x)) if x else '')

tmp

,order_id,product_name,product_id,bought_product_id,product_external_id,bought_product_quantity,replaced_by_bought_product_id,replaced_bought_product_id
1,100382450564,"Mleczna Dolina Masło Ekstra bez laktozy 82%, 2...",24083945264,105352420838,287045,1,,
2,100382450564,"Cukier biały, 1 kg",23833875690,105352420858,291534,1,,
3,100382450564,"Bonitki Sezamki Classic, 3x27 g",21328063111,105352420841,286678,1,,
4,100382450564,"Mleczna Dolina Mleko UHT bezlaktozy 3,2%, 1 L",24888235704,105352420845,283084,2,,
5,100382450564,"Nestlé Cheerios Płatki śniadaniowe, 275 g",23794199926,105352420846,1082,1,,
6,100382450564,"Delicje Szampańskie pomarańczowe, 147 g",19636840435,105352420822,307686,1,,
7,100382450564,"Cukiernia Róża Rurki waflowe Waniliowe, 280 g",24502714041,105352420842,2042631,2,,
8,100382450564,"Kamis Przyprawa do mięsa mielonego, 20 g",17434756134,105352420827,358746,1,,
9,100382450564,Torba T-shirt BIEK 1 szt,24279534084,105352522441,409893,0,105352522442,
10,100382450564,"Nasze Smaki Pierogi z mięsem i cebulką bowl, 3...",24888227069,105352420824,384891,1,,
40,100382450564,"Tchibo Family Kawa mielona, 500 g",13068511144,105352420852,201996,1,,
41,100382450564,GustoBello Pomidory krojone z cebulą i czosnki...,24888227068,105352420825,3790292,1,,
42,100382450564,"TOP Tortilla Chipsy serowe, 150 g",24923174381,105352420854,2076032,1,,
43,100382450564,Aril Świeca zapachowa w szkle frezja i gruszka...,24011061932,105352420821,3773732,1,,
44,100382450564,"Fruvita Jogurt z granolą i truskawkami, 230 g",23975114144,105352420833,3609811,1,,
45,100382450564,"Drobimex Pierś pieczona, 100 g",24402333549,105352420828,2830101,1,,
46,100382450564,"Pastani Makaron durum Penne, 500 g",24573432699,105352420848,195157,1,,
47,100382450564,"Mlekovita Mleko czekoladowe, 200 ml",24702088018,105352420823,302440,1,,
48,100382450564,"Nasze Smaki Pierogi z serem, 400 g",24193843155,105352420843,265027,2,,
49,100382450564,Zosia Samosia Woreczki śniadaniowe zawiązywane...,16212495423,105352420856,298597,1,,
50,100382450564,"Żywiec Zdrój Woda źródlana mocno gazowana, 1,75 L",24279536124,105352420850,208155,1,,
51,100382450564,"Cebula Szalotka, 1 szt. ok. 50 g, 9,90/kg",24356175124,105352420837,370188,2,105352522429,
52,100382450564,Blend-a-med Pasta do zębów 3D White Extreme Mi...,24888235727,105352420839,4139052,1,,
53,100382450564,"Milka Pieguski Ciastka z czekoladą, 300 g",24888226745,105352420844,275701,1,,
54,100382450564,"Dare Wafel w ciemnej czekoladzie, 50 g",17907358205,105352420835,382057,2,,
55,100382450564,"Queen Papier Toaletowy Premium Super Soft, 10 ...",24279536944,105352420829,358909,1,,
56,100382450564,"Vital Fresh Smoothie imbir jabłko banan kokos,...",24888235745,105352420826,477627,1,,
57,100382450564,"Mr Potato Ziemniaczki, 750 g",24193843392,105352420851,206432,1,,
58,100382450564,"Drobimex Szynka delikatesowa z kurcząt, 100 g",24534005537,105352420857,2830102,2,,
59,100382450564,"Culineo Sól warzona jodowana, 1 kg",24502714625,105352420860,198521,1,,
60,100382450564,"Fairy Sensitive Płyn do mycia naczyń, drzewo h...",24702087736,105352420855,4284804,1,,
61,100382450564,"Milka Czekolada Toffee Wholenut, 300 g",24573431189,105352420832,2594092,1,,
62,100382450564,"Bataty Słodkie ziemniaki, 1 szt. ok. 350 g, 9,...",24888235886,105352420831,266649,1,,
63,100382450564,"TOP Chrupki z soczewicy paprykowe, 70 g",22687889597,105352420859,4097891,1,,
64,100382450564,"Delikate Serek wiejski klasyczny, bez laktozy,...",24193843272,105352420853,279090,1,,
65,100382450564,"Pastani Makaron durum Fusilli, 500 g",24402337508,105352420830,195158,1,,
66,100382450564,"Sierpc Ser żółty Królewski Light w plastrach, ...",24888226751,105352420847,3023331,1,,
67,100382450564,Torba T-shirt BIEK 1 szt,24279534084,105352522442,409893,4,,105352522441
68,100382450564,"Torebka na wino, 1 szt.",22730006781,105352420836,25218117,1,,
69,100382450564,"Wedel Wafelek WW w mlecznej czekoladzie, 47 g",24502715069,105352420840,278495,1,,
70,100382450564,"Herbapol Mięta, 20 torebek",18848941869,105352420849,421252,1,,
71,100382450564,"Cebula Szalotka, 1 szt. ok. 50 g, 9,90/kg",24356175124,105352522429,370188,3,,105352420837
72,100382450564,"Hellena Oranżada czerwona, 1,25 L",23299653858,105352420834,463780,1,,

## Task 3: % of orders with additions

In [51]:
#query object
q = query_engines.QueryEngines(
    query='perc_orders_with_additions.sql', 
    params=None,
    load_from_output_file=None, #with no .csv
    output_file=None, #with no .csv
    printq=None
)

df = q.query_run_starbust()
df

c:\Users\Jordi Cremades\Documents\Repository\utils\query_engines.py:145: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(self.tp__read_query, conn)

Open the following URL in browser for the external authentication:
https://starburst.g8s-data-platform-prod.glovoint.com/oauth2/token/initiate/a78da5d4b5446bfd576eea8c2994737f137d44ef7c418ec0c9eee38a8f27f1b0

   n_orders  n_orders_with_additions
0   2493554                   497416

In [53]:
df['perc_orders_with_additions'] = df['n_orders_with_additions']/df['n_orders']
df

   n_orders  n_orders_with_additions  perc_orders_with_additions
0   2493554                   497416                    0.199481